In [1]:
import numpy as np

In [2]:
data = [0.9454, -0.325, -0.8854, 0.5464, 0.2354, 0.9194]

In [3]:
arr1 = np.array (data)

In [4]:
arr1

array([ 0.9454, -0.325 , -0.8854,  0.5464,  0.2354,  0.9194])

1. I see the contents of the ndarray arr1.

In [5]:
arr1*10

array([ 9.454, -3.25 , -8.854,  5.464,  2.354,  9.194])

 2. I see the contents of the arr1 ndarray multiplied by 10.

In [6]:
arr1+arr1

array([ 1.8908, -0.65  , -1.7708,  1.0928,  0.4708,  1.8388])

3. I see the contents of the arr1 ndarray added to itself.

In [7]:
arr1.shape

(6,)

4. arr1.shape shows the size of the array.

In [9]:
arr1.dtype

dtype('float64')

5. arr1.dtype shows the data type of the array.

In [11]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

6. arr2.ndim shows the dimensions of the array.

In [15]:
arr2.shape

(2, 4)

7. the left side value shows the number of columns while the right side value shows the number of rows.

In [16]:
arr2.dtype

dtype('int64')

8. arr1's dtype is float64 since floating-point decimal values are present, while arr2's dtype is int64 since only integers are present.

In [17]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [18]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

10. np.zeros_like() copies the shape of the array used as its argument.

In [19]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [20]:
np.empty((2,3,2))

array([[[  6.91412648e-310,   2.73083679e-316],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   5.69616879e-066]],

       [[  2.52618878e-052,   3.88390828e-057],
        [  1.46371286e-047,   6.09658108e+170],
        [  4.12516957e-061,   7.67125088e-042]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])